# Generated by Django 5.0.1 on 2024-02-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
